config/routes.rb
Rails.application.routes.draw do
  resources :frees
  resources :as
  resources :jobs
  resources :posts
 devise_for :users
 root "pages#home"
 get "about" => "pages#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/a.rb
class A < ApplicationRecord
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/free.rb
class Free < ApplicationRecord
  belongs_to :user
end

app/models/freelance.rb
class Freelance < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord

	belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :as
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/as_controller.rb
class AsController < ApplicationController
  before_action :set_a, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show ]


  def index
    @as = A.all
  end


  def show
  end


  def new
    @a = current_user.as.build
  end

 
  def edit
  end


  def create
    @a = current_user.as.build(a_params)
  


      if @a.save
        redirect_to @a, notice: 'A was successfully created.' 
        
      else
        render :new 
       
      end
      end



  def update
  
      if @a.update(a_params)
        redirect_to @a, notice: 'A was successfully updated.' 
       
      else
        render :edit 
      
      end

  end

 
  def destroy
    @a.destroy
    
      redirect_to as_url, notice: 'A was successfully destroyed.' 
      
  end

  private
    
    def set_a
      @a = A.find(params[:id])
    end

    def correct_user
      @a = current_user.as.find_by(id: params[:id])
      redirect_to as_path if @a.nil?
    end

   
    def a_params
      params.require(:a).permit(:description)
    end
end

app/controllers/freelances_controller.rb
class FreelancesController < ApplicationController
  before_action :set_freelance, only: [:show, :edit, :update, :destroy]

  # GET /freelances
  # GET /freelances.json
  def index
    @freelances = Freelance.all
  end

  # GET /freelances/1
  # GET /freelances/1.json
  def show
  end

  # GET /freelances/new
  def new
    @freelance = Freelance.new
  end

  # GET /freelances/1/edit
  def edit
  end

  # POST /freelances
  # POST /freelances.json
  def create
    @freelance = Freelance.new(freelance_params)

    respond_to do |format|
      if @freelance.save
        format.html { redirect_to @freelance, notice: 'Freelance was successfully created.' }
        format.json { render :show, status: :created, location: @freelance }
      else
        format.html { render :new }
        format.json { render json: @freelance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /freelances/1
  # PATCH/PUT /freelances/1.json
  def update
    respond_to do |format|
      if @freelance.update(freelance_params)
        format.html { redirect_to @freelance, notice: 'Freelance was successfully updated.' }
        format.json { render :show, status: :ok, location: @freelance }
      else
        format.html { render :edit }
        format.json { render json: @freelance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /freelances/1
  # DELETE /freelances/1.json
  def destroy
    @freelance.destroy
    respond_to do |format|
      format.html { redirect_to freelances_url, notice: 'Freelance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_freelance
      @freelance = Freelance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def freelance_params
      params.require(:freelance).permit(:description)
    end
end

app/controllers/frees_controller.rb
class FreesController < ApplicationController
  before_action :set_free, only: [:show, :edit, :update, :destroy]

  # GET /frees
  # GET /frees.json
  def index
    @frees = Free.all
  end

  # GET /frees/1
  # GET /frees/1.json
  def show
  end

  # GET /frees/new
  def new
    @free = Free.new
  end

  # GET /frees/1/edit
  def edit
  end

  # POST /frees
  # POST /frees.json
  def create
    @free = Free.new(free_params)

    respond_to do |format|
      if @free.save
        format.html { redirect_to @free, notice: 'Free was successfully created.' }
        format.json { render :show, status: :created, location: @free }
      else
        format.html { render :new }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frees/1
  # PATCH/PUT /frees/1.json
  def update
    respond_to do |format|
      if @free.update(free_params)
        format.html { redirect_to @free, notice: 'Free was successfully updated.' }
        format.json { render :show, status: :ok, location: @free }
      else
        format.html { render :edit }
        format.json { render json: @free.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frees/1
  # DELETE /frees/1.json
  def destroy
    @free.destroy
    respond_to do |format|
      format.html { redirect_to frees_url, notice: 'Free was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
def create
  @post = Post.new(post_params) do |post|
    post.user = current_user
  end
  if @post.save
    redirect_to root_path
  else
    redirect_to root_path, notice: @post.errors.full_messages.first
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_free
      @free = Free.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def free_params
      params.require(:free).permit(:attachment, :content, :user_id)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]


  def index
    @jobs = Job.all
  end

 
  def show
  end

  
  def new
    @job = Job.new
  end

 
  def edit
  end

  
  def create
    @job = Job.new(job_params)

    
      if @job.save
        redirect_to @job, notice: 'Job was successfully created.' 
        
      else
        render :new 
        
      end
  end

  def update
    
      if @job.update(job_params)
        redirect_to @job, notice: 'Job was successfully updated.' 
        
      else
        render :edit 
        
      end
  end

  
  def destroy
    @job.destroy
    
      redirect_to jobs_url, notice: 'Job was successfully destroyed.' 
      
  end

  private
    
    def set_job
      @job = Job.find(params[:id])
    end

   
    def job_params
      params.require(:job).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  
  def index
    @posts = Post.all
  end

 
  def show
  end


  def new
    @post = current_user.posts.build
  end

 
  def edit
  end


  def create
    @post = Post.new(post_params)
    post.user 

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.' 
        
      else
         render :new 
        
      end
  end

  
  def update
    
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.' 
        
      else
        render :edit 
        
      end
  end

  def destroy
    @post.destroy
   
      redirect_to posts_url, notice: 'Post was successfully destroyed.' 
      
    
  end





  private
   
    def set_post
      @post = Post.find(params[:id])
    end

    
    def post_params
      params.require(:post).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/as_helper.rb
module AsHelper
end

app/helpers/freelances_helper.rb
module FreelancesHelper
end

app/helpers/frees_helper.rb
module FreesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/as/_form.html.erb
<%= form_for(a) do |f| %>
  <% if a.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(a.errors.count, "error") %> prohibited this a from being saved:</h2>

      <ul>
      <% a.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/as/edit.html.erb
<h1>Editing A</h1>

<%= render 'form', a: @a %>

<%= link_to 'Show', @a %> |
<%= link_to 'Back', as_path %>

app/views/as/index.html.erb
<p id="notice"><%= notice %></p>

<h1>As</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
       <th>user_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @as.each do |a| %>
      <tr>
        <td><%= a.description %></td>
         <td><%= a.user.email if a.user %></td>
        <td><%= link_to 'Show', a %></td>
        <% if a.user == current_user%>
          <td><%= link_to 'Edit', edit_a_path(a) %></td>
          <td><%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New A', new_a_path %>
<% end %>

app/views/as/new.html.erb
<h1>New A</h1>

<%= render 'form', a: @a %>

<%= link_to 'Back', as_path %>

app/views/as/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @a.description %>
</p>



<% if @a.user == current_user %>
<%= link_to 'Edit', edit_a_path(@a) %> |
<% end %>
<%= link_to 'Back', as_path %>

app/views/frees/_form.html.erb
<%= form_for(free) do |f| %>
  <% if free.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(free.errors.count, "error") %> prohibited this free from being saved:</h2>

      <ul>
      <% free.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attachment %>
    <%= f.text_field :attachment %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= f.label 'Update status' %><br>
      <%= f.text_area :content, class: 'form-control', autofocus: true, 
          placeholder: 'What\'s up?' %>
      <%= f.file_field :attachment, class: 'form-control' %>
  </div>
  <%= f.submit :post, class: 'btn btn-primary'%>
<% end %>

app/views/frees/edit.html.erb
<h1>Editing Free</h1>

<%= render 'form', free: @free %>

<%= link_to 'Show', @free %> |
<%= link_to 'Back', frees_path %>

app/views/frees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Frees</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frees.each do |free| %>
      <tr>
        <td><%= free.attachment %></td>
        <td><%= free.content %></td>
        <td><%= free.user %></td>
        <td><%= link_to 'Show', free %></td>
        <td><%= link_to 'Edit', edit_free_path(free) %></td>
        <td><%= link_to 'Destroy', free, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Free', new_free_path %>

app/views/frees/new.html.erb
<h1>New Free</h1>

<%= render 'form', free: @free %>

<%= link_to 'Back', frees_path %>

app/views/frees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attachment:</strong>
  <%= @free.attachment %>
</p>

<p>
  <strong>Content:</strong>
  <%= @free.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @free.user %>
</p>

<%= link_to 'Edit', edit_free_path(@free) %> |
<%= link_to 'Back', frees_path %>

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style type="text/css">
  


.overdiv-index_posts {
  position: relative;
  margin-left: auto;
  margin-right: auto;
  border-right: 1px solid blue;
  border-left: 1px solid blue;
  width: 1000px;
  top: -8px;
  height: 500px;
  min-width: 1000px;
  font-weight: 300;
}

</style>

<div class='overdiv-index_posts'>

<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Freelance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>